title: "Johan's Cloud Blog"
name: Johan Grant
email: mail@johangrant.cloud

# description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

# social_links:
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
linkedin: johangrant
github_username:  grantjo78 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage


theme: minima

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-feed
  - jekyll-seo-tag